### ISSUE TITLE
website

### ISSUE THREAD

**Issue by Croydon** [skelsec/BitErrant#3]
Could you maybe make the content of the now gone website http://biterrant.io somewhere available?

You could use GitHub Pages pretty easily for this. Just push the content of the website in a new branch (or new repository if you prefer this). See https://pages.github.com and https://help.github.com/articles/what-is-github-pages/

Thank you!

**Comment by skelsec** [comment]
Good call! Website is up and running now.
Will upload the content sometime.

**Comment by kovalensky** [comment]
> Good call! Website is up and running now. Will upload the content sometime.

How about now? :)
